name: Job Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      INDEED_QUERY: ${{ secrets.INDEED_QUERY }}
      INDEED_LOCATION: ${{ secrets.INDEED_LOCATION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job alert script
        run: python job_alert.py
